version: "3.9"
services:
    np_api:
        container_name: np_api
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        # env_file:
        #     - .env.local
        # depends_on:
        #   - postgres
        #   - redis
        ports:
            - 4000:4000
